### ISSUE TITLE
How do you add LD_PRELOAD to your config?

### ISSUE THREAD

**Issue by Lillian-Violet** [chaorace/extest-nix#1]
Hey, in your readme you specify in step 3: "Append the shared object to Steam’s LD_PRELOAD " but I have no idea where this snippet goes? I put the first step in flake.nix, the second step in the configuration for my system, but I have no idea where this third step should go. If you could give me a pointer that'd be great thank you.

**Comment by chaorace** [comment]
Hey, thanks for reaching out!

The snippet you're referencing is an override to the `steam` package. This means that the snippet behaves exactly like the normal Steam package in terms of how it works and where it's supposed to go. Think of it like a remixed package.

Since the snippet is functionally a new version of the `steam` package, it should replace the `steam` package wherever you would normally define it in your specific use-case. The exact details will tend to vary, but here are some examples covering what I feel are the most common scenarios:

## NixOS (`programs.steam.enable`)
NixOS has a standard option for enabling Steam via `programs.steam.enable`. If this is how you're using Steam, it means you need to use the related `programs.steam.package` option to replace the default `steam` package with the overridden version from the readme snippet:

**/etc/nixos/configuration.nix**
```
programs.steam.enable = true;
programs.steam.package = (pkgs.steam.override {
  extraProfile = ''export LD_PRELOAD=${pkgs.extest}/lib/libextest.so:$LD_PRELOAD'';
});
```

## NixOS (`environment.systemPackages`)
NixOS also has a general option for installing packages via `environment.systemPackages`. If you're on NixOS and not using `programs.steam.enable`, then this list is probably where your `steam` package is being declared.

Since the override represents an extended version of the base `steam` package, you'll need to remove the original `steam` package from this list and replace it with the readme snippet.

**/etc/nixos/configuration.nix**
```
environment.systemPackages = with pkgs; [
  [[[... other packages ...]]]
  (steam.override {
    extraProfile = ''export LD_PRELOAD=${pkgs.extest}/lib/libextest.so:$LD_PRELOAD'';
  })
  [[[... other packages ...]]]
];
```

## Home Manager (`home.packages`)
If you've installed `steam` via home-manager, then it is most likely defined via the `home.packages` list. This is very similar to the prior `environment.systemPackages` scenario... only with a different option name. For the same reasons mentioned in the prior scenario, you will need to remove the original `steam` package from the list and replace it with the overridden version from the readme snippet.

One wrinkle unique to home-manager is that it can be installed standalone *or* as a NixOS module. They're functionally identical for our purposes, though it does *slightly* change how the configuration should look, so I've included examples for both:

**(Standalone) ~/.config/home-manager/home.nix**
```
home.packages = with pkgs; [
  [[[... other packages ...]]]
  (steam.override {
    extraProfile = ''export LD_PRELOAD=${pkgs.extest}/lib/libextest.so:$LD_PRELOAD'';
  })
  [[[... other packages ...]]]
];
```

**(NixOS Module) /etc/nixos/configuration.nix**
```
home-manager.users.[[[your username]]] = {
  home.packages = with pkgs; [
    [[[... other packages ...]]]
    (steam.override {
      extraProfile = ''export LD_PRELOAD=${pkgs.extest}/lib/libextest.so:$LD_PRELOAD'';
    })
    [[[... other packages ...]]]
  ];
};
```

**Comment by Lillian-Violet** [comment]
Thank you so much for the detailed explanation, very helpful, hope you have a lovely day!
